// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icwdxhfslqojuwizdrqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd2R4aGZzbHFvanV3aXpkcnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNTA2OTcsImV4cCI6MjA5MDcyNjY5N30.4aRXM5JlEj0ragwJUdAjUAXO8hbbNngeJBxFnJASKFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});